title: "[날짜 작성]"
body:
  - type: markdown
      value: "## 주제!"
  - type: textarea
    attributes:
      label: "📋 회의 내용"
      value: |
        *
        *
        *
  - type: textarea
    attributes:
      label: "🦋 알게된 사실 or 참고 자료"
      value: |
        *
        *
        *
    validations:
      required: true
